---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tesbacad/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan storage:link
    - php artisan optimize
    - chmod -R 755 storage bootstrap/cache