name: Deploy cPanel via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          cat .env

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
      - name: Install Node Dependencies
        run: npm install
      - name: Build Node Dependencies
        run: npm run build
      - name: Fix Permissions
        run: |
          find storage -type d -exec chmod 775 {} \;
          find bootstrap/cache -type d -exec chmod 775 {} \;
          
      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_DEPLOY_PATH }}
          exclude: |
            .git*
            .github/
            .env
            node_modules/
