name: Laravel

on:
  push:
    branches: [ "main" ]
     
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Create .env
      run: |
        touch .env
        echo "${{ secrets.ENV }}" > .env
        cat .env
    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Install Node Dependencies
      run: npm install
    - name: Build Node Dependencies
      run: npm run build
    - name: Directory Permissions
      run: chmod -R 775 storage bootstrap/cache
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        dangerous-clean-slate: true 
